(Отпуски) --> (Одобрения/отклонение отпуска)
(Отпуски) --> (Конкретный отпуск)

(Командировки) --> (Создание командировки)
(Командировки) --> (Конкретная командировка)

(Конкретная командировка) --> (Редактирование командировки)
(Конкретная командировка) --> (Удаление командировки)