(Рядовые сотрудники) --> (Создать сотрудника)
(Рядовые сотрудники) --> (Конкретный сотрудник)

(Руководители) --> (Создать руководителя)
(Руководители) --> (Конкретный руководитель)

(Конкретный сотрудник) --> (Редактировать сотрудника)
(Конкретный сотрудник) --> (Удалить сотрудника)

(Конкретный руководитель) --> (Редактировать руководителя)
(Конкретный руководитель) --> (Удалить руководителя)