(Праздники) --> (Добавить праздник)
(Праздники) --> (Конкретный праздник)

(Должности) --> (Создать должность)
(Должности) --> (Конкретная должность)

(Конкретный праздник) --> (Редактировать праздник)
(Конкретный праздник) --> (Удалить праздник)

(Конкретная должность) --> (Редактировать должность)
(Конкретная должность) --> (Удалить должность)