@startuml

left to right direction

actor "Администратор" as Admin

Admin --> (Авторизация)
(Авторизация) --> (Главный экран)

(Главный экран) --> (Рядовые сотрудники)
(Главный экран) --> (Руководители)
(Главный экран) --> (Праздники)
(Главный экран) --> (Должности)
(Главный экран) --> (Отделы)
(Главный экран) --> (Отпуски)
(Главный экран) --> (Командировки)
(Главный экран) --> (Отчеты сотрудников)
(Главный экран) --> (Совпадает с руководителем)

(Рядовые сотрудники) --> (Создать сотрудника)
(Рядовые сотрудники) --> (Конкретный сотрудник)

(Руководители) --> (Создать руководителя)
(Руководители) --> (Конкретный руководитель)

(Праздники) --> (Добавить праздник)
(Праздники) --> (Конкретный праздник)

(Должности) --> (Создать должность)
(Должности) --> (Конкретная должность)

(Отделы) --> (Создать отдел)
(Отделы) --> (Конкретный отдел)

(Отпуски) --> (Удалить отпуски)
(Командировки) --> (Удалить командировки)
(Отчеты сотрудников) --> (Удалить отчеты)

(Конкретный сотрудник) --> (Редактировать сотрудника)
(Конкретный сотрудник) --> (Удалить сотрудника)

(Конкретный руководитель) --> (Редактировать руководителя)
(Конкретный руководитель) --> (Удалить руководителя)

(Конкретный праздник) --> (Редактировать праздник)
(Конкретный праздник) --> (Удалить праздник)

(Конкретная должность) --> (Редактировать должность)
(Конкретная должность) --> (Удалить должность)

(Конкретный отдел) --> (Редактировать отдел)
(Конкретный отдел) --> (Удалить отдел)

@enduml