@startuml


actor "Руководитель" as Manager

Manager --> (Авторизация)
(Авторизация) --> (Главный экран)

(Главный экран) --> (Подчиненные сотрудники)
(Главный экран) --> (Проекты)
(Главный экран) --> (Задачи)
(Главный экран) --> (Отпуски)
(Главный экран) --> (Командировки)
(Главный экран) --> (Совпадает с рядовым сотрудником)