actor "Администратор" as Admin

Admin --> (Авторизация)
(Авторизация) --> (Главный экран)

(Главный экран) --> (Рядовые сотрудники)
(Главный экран) --> (Руководители)
(Главный экран) --> (Праздники)
(Главный экран) --> (Должности)
(Главный экран) --> (Отделы)
(Главный экран) --> (Отпуски)
(Главный экран) --> (Командировки)
(Главный экран) --> (Отчеты сотрудников)
(Главный экран) --> (Совпадает с руководителем)