@startuml



(История отчётов) --> (Просмотр отчета)
(Просмотр отчета) --> (Редактирование отчета)

(Управление задачами) --> (Просмотр задачи)
(Просмотр задачи) --> (Принятие задания)
(Просмотр задачи) --> (Завершение задания)
(Просмотр задачи) --> (Отказ от задания)

(Создание отчета) --> (Ввод рабочего времени)
(Создание отчета) --> (Ввод выполнявшихся задач)

@enduml