(Отделы) --> (Создать отдел)
(Отделы) --> (Конкретный отдел)

(Отпуски) --> (Удалить отпуски)

(Конкретный отдел) --> (Редактировать отдел)
(Конкретный отдел) --> (Удалить отдел)

(Командировки) --> (Удалить командировки)
(Отчеты сотрудников) --> (Удалить отчеты)
