@startuml


actor "Руководитель" as Manager

Manager --> (Авторизация)
(Авторизация) --> (Главный экран)

(Главный экран) --> (Подчиненные сотрудники)
(Главный экран) --> (Проекты)
(Главный экран) --> (Задачи)
(Главный экран) --> (Отпуски)
(Главный экран) --> (Командировки)
(Главный экран) --> (Совпадает с рядовым сотрудником)

(Подчиненные сотрудники) --> (Конкретный сотрудник)
(Подчиненные сотрудники) --> (Фильтрация сотрудников)

(Проекты) --> (Создание проекта)
(Проекты) --> (Конкретный проект)

(Задачи) --> (Создание задачи)
(Задачи) --> (Конкретная задача)

(Отпуски) --> (Одобрения/отклонение отпуска)
(Отпуски) --> (Конкретный отпуск)

(Командировки) --> (Создание командировки)
(Командировки) --> (Конкретная командировка)

(Конкретный сотрудник) --> (История отчётов)
(Конкретный сотрудник) --> (Список задач)
(Конкретный сотрудник) --> (Назначить проект)
(Конкретный сотрудник) --> (Назначить задачу)
(Конкретный сотрудник) --> (Рабочий график)

(Конкретный проект) --> (Редактирование)
(Конкретный проект) --> (Удаление)
(Конкретный проект) --> (Добавить задачу)

(Конкретная задача) --> (Редактирование задачи)
(Конкретная задача) --> (Удаление задачи)

(Конкретная командировка) --> (Редактирование командировки)
(Конкретная командировка) --> (Удаление командировки)

(Рабочий график) --> (Редактирование графика сотрудника)

(Список задач) --> (Просмотр конкретной задачи)

(История отчётов) --> (Просмотр отчета)
(Просмотр отчета) --> (Редактирование отчета)

@enduml