(Проекты) --> (Создание проекта)
(Проекты) --> (Конкретный проект)

(Задачи) --> (Создание задачи)
(Задачи) --> (Конкретная задача)

(Конкретный проект) --> (Редактирование)
(Конкретный проект) --> (Удаление)
(Конкретный проект) --> (Добавить задачу)

(Конкретная задача) --> (Редактирование задачи)
(Конкретная задача) --> (Удаление задачи)