(Подчиненные сотрудники) --> (Конкретный сотрудник)
(Подчиненные сотрудники) --> (Фильтрация сотрудников)

(Конкретный сотрудник) --> (История отчётов)
(Конкретный сотрудник) --> (Список задач)
(Конкретный сотрудник) --> (Назначить проект)
(Конкретный сотрудник) --> (Назначить задачу)
(Конкретный сотрудник) --> (Рабочий график)

(История отчётов) --> (Просмотр отчета)
(Просмотр отчета) --> (Редактирование отчета)

(Рабочий график) --> (Редактирование графика сотрудника)

(Список задач) --> (Просмотр конкретной задачи)