@startuml

!pragma useVerticalIf on
start

:Пользователь открывает приложение;


repeat 
    :Пользователь вводит\n логин и пароль;
repeat while (Логин и пароль корректны?) is (нет) not (да)

:Пользователь успешно вошел;
:Показать окно загрузки;
:Загрузить данные пользователя;
:Показать главный экран приложения;


'if(Логин и пароль корректны?) then ()
'else()
'endif




stop

@enduml