@startuml

!pragma useVerticalIf on
start

:Пользователь вошел в систему;
:Пользователь нажал кнопку "История отчетов";
:Показать пользователю его отчеты;
while (Пользователь ушел с вкладки история отчетов?) is (нет)
    
    if(Пользователь нажал на конкретный отчет?) then (да)
        :Открыть пользователю этот отчет;
        :Позволить пользователю редактировать отчет;
        while (Пользователь закрыл конкретный отчет?) then (нет)
            if (Пользователь нажал на кнопку сохранить?) then (да)
                :Валидация ввода;
                if (Данные корректны?) then (да)
                    :Сохранить данные;
                    :Оповестить пользователя, что сохранение прошло успешно;
                else(нет)
                    :Предупредить пользователя, что данные не корректны;
                    :Установить, что кнопку сохранить не нажимали;
                endif
            endif
        endwhile (да)
        :Показать пользователю его отчеты;    
    endif 
endwhile (да)

stop

@enduml