@startuml
actor "Пользователь" as user
'autonumber
participant "Интерфейс" as ui
participant "Ядро приложения" as app
database "База данных" as db

' activate user
user++
user -> ui++: Ввод логина и пароля
user -> ui: Нажатие [авторизация]
ui -> app++: Логин, пароль и \nзапрос на авторизацию
app ->> db++: Логин, пароль и \nзапрос на поиск
db -->> app--: Найден ли пользователь
app -->> ui--: Найден ли пользователь
ui -->> user: Главное окно или ошибку
ui -> user--: Иконку загрузки
user--

app++
app ->> db++: Запрос на все данные пользователя
db -->> app--: Все данные пользователя
app -> ui--++: Данные загружены
ui -> user--: Убирает иконку загрузки 


user++
user -> ui++: Нажатие [история отчетов]
ui -> app++: Запрос на историю отчетов
app -->> ui--: История отчетов
ui -->> user--: История отчетов 

user -> ui++: Выбирает конкретный отчет
ui -> app++: Запрос на конкретный отчет
app -->> ui--: Конкретный отчет
ui -->> user--: Показывает конкретный отчет
user -> ui++: Редактирует отчет
user -> ui: Нажимает [сохранить]
ui -> app: Запрос на обновление
app ->> db++: Запрос на обновление отчета
db -->> app--: Ответ на запрос
app -->> ui--: Ответ на запрос
ui -->> user--: Результат сохранения

user -> ui++: Нажимает [закрыть приложение]
ui -> app++: Оповещение о закрытии
app++
app--
ui--
user--


'->  обычное'
'->> асинхронное'
'-->> ответ'
@enduml



'@startuml
'actor "Front" as front
'autonumber
'box "Back" #LightBlue
'participant "Сервис банкоматов и отделений" as atm
'database "База данных" as db
'end box
'box "External Service" #LightYellow
'participant "Yandex" as yandex
'end box
'front -> atm++: Запрос на получение \nсписка банкоматов и отделений
'atm -> db++:  Получение списка банкоматов \nи отделений из БД
'db -> db:  Получение данных
'db --> atm--:  Данные банков и отделений
'atm --> yandex++:  Получение адресного перечня \nпо сохраненным координатам
'yandex -> atm--: Адресный перечень
'atm ->  front--:  Список банкоматов и отделений с адресами
'@enduml